- name: deploy docker compose artifacts
  hosts: docker
  tasks:
    - name: copy atifacts
      copy: src=docker-app/ dest=/root/docker_bday_oc_artifacts/

    - name: deploy docker app
      docker-compose: docker_compose_config_path="/root/docker_bday_oc_artifacts/"
